#!/bin/sh
if [ -z "$1" ]; then
    echo "Usage: wh file.html > full.html"
    exit
fi

if [ ! -f "$1" ]; then
    echo "file not found"
    exit
fi

cat << EOF
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<body>
EOF

cat $1

cat << EOF
</body>
</html>
EOF
